using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;
using System.Text;

namespace TiroSetup.Services
{
    /// <summary>Everything Setup downloads, with sizes and SHA-256 (generated by tools/package_release.py).</summary>
    [DataContract]
    public sealed class Manifest
    {
        [DataMember(Name = "version")] public string Version;
        [DataMember(Name = "repo")] public string Repo;
        [DataMember(Name = "app")] public Package App;
        [DataMember(Name = "gpu")] public Package Gpu;
        [DataMember(Name = "models")] public Dictionary<string, ModelEntry> Models;

        public static Manifest Load()
        {
            using (var s = Assembly.GetExecutingAssembly().GetManifestResourceStream("manifest.json"))
            {
                var settings = new DataContractJsonSerializerSettings { UseSimpleDictionaryFormat = true };
                return (Manifest)new DataContractJsonSerializer(typeof(Manifest), settings).ReadObject(s);
            }
        }
    }

    [DataContract]
    public sealed class Package
    {
        [DataMember(Name = "url")] public string Url;
        [DataMember(Name = "size")] public long Size;
        [DataMember(Name = "sha256")] public string Sha256;
        [DataMember(Name = "installed_bytes")] public long InstalledBytes;
    }

    [DataContract]
    public sealed class ModelEntry
    {
        [DataMember(Name = "title")] public string Title;
        [DataMember(Name = "subtitle")] public string Subtitle;
        [DataMember(Name = "folder")] public string Folder;
        [DataMember(Name = "repo")] public string Repo;
        [DataMember(Name = "revision")] public string Revision;
        [DataMember(Name = "fp32")] public List<ModelFile> Fp32;
        [DataMember(Name = "int8")] public List<ModelFile> Int8;

        public List<ModelFile> Files(bool fullPrecision) => fullPrecision ? Fp32 : Int8;
        public long Size(bool fullPrecision) => Files(fullPrecision).Sum(f => f.Size);
    }

    [DataContract]
    public sealed class ModelFile
    {
        [DataMember(Name = "name")] public string Name;
        [DataMember(Name = "url")] public string Url;
        [DataMember(Name = "size")] public long Size;
        [DataMember(Name = "sha256")] public string Sha256;
    }
}
