"""Short, quiet UI cues (generated by tools/make_assets.py)."""

from __future__ import annotations

import winsound

from tiro.paths import asset

_FLAGS = winsound.SND_FILENAME | winsound.SND_ASYNC | winsound.SND_NODEFAULT


def play(name: str) -> None:
    path = asset("sounds", f"{name}.wav")
    if path.is_file():
        try:
            winsound.PlaySound(str(path), _FLAGS)
        except RuntimeError:
            pass
