# Build Tiro.exe (one-folder PyInstaller app) into build\dist\Tiro, ready to run locally, then package the
# release downloads (tools\package_release.py) and the installer (installer\build.ps1).
# Usage:  powershell -ExecutionPolicy Bypass -File tools\build.ps1 [-SkipInstaller]
# Test builds for the end-to-end update tests (never released):
#   tools\build.ps1 -TestVersion 9.0.0 -TestKey <base64 public key> -NoCuda -Dist build\e2e -SkipInstaller -SkipPackage
param([switch]$SkipInstaller, [switch]$SkipPackage, [string]$TestVersion = "", [string]$TestKey = "",
      [string]$TestCrash = "", [switch]$NoCuda, [string]$Dist = "")
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$py = Join-Path $root ".venv\Scripts\python.exe"
$dist = if ($Dist) { Join-Path $root $Dist } else { Join-Path $root "build\dist" }
$buildFile = Join-Path $root "tiro\_build.py"

# tiro/_build.py exists only while a test build is being made; a release build never has it
if (Test-Path $buildFile) { Remove-Item $buildFile -Force }
if ($TestVersion) {
    $lines = @("# generated by tools/build.ps1 for a TEST build; deleted after the build", "VERSION = `"$TestVersion`"")
    if ($TestKey) { $lines += "TEST_KEYS = {`"e2e-test`": `"$TestKey`"}" } else { $lines += "TEST_KEYS = {}" }
    if ($TestCrash) { $lines += "CRASH_ON_TRIAL = True" }
    [System.IO.File]::WriteAllLines($buildFile, $lines)
}
try {
    & $py (Join-Path $root "tools\make_assets.py")
    if ($LASTEXITCODE -ne 0) { throw "asset generation failed" }

    & powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root "tools\build_native.ps1")
    if ($LASTEXITCODE -ne 0) { throw "native build failed" }

    if ($NoCuda) { $env:TIRO_BUILD_NO_CUDA = "1" } else { Remove-Item Env:TIRO_BUILD_NO_CUDA -ErrorAction SilentlyContinue }
    & $py -m PyInstaller --noconfirm --clean --distpath $dist --workpath (Join-Path $root "build\work") (Join-Path $root "tiro.spec")
    if ($LASTEXITCODE -ne 0) { throw "PyInstaller failed" }
} finally {
    if (Test-Path $buildFile) { Remove-Item $buildFile -Force }
    Remove-Item Env:TIRO_BUILD_NO_CUDA -ErrorAction SilentlyContinue
}
if ($TestVersion) { Write-Host "Test build $TestVersion -> $dist\Tiro"; return }

# Local copy of the models next to the exe (hard links: no extra disk space). Release zips leave them out;
# the installer downloads them from Hugging Face.
$app = Join-Path $dist "Tiro"
foreach ($m in "parakeet-tdt-0.6b-v2", "silero-vad", "qwen2.5-1.5b-instruct", "qwen2.5-0.5b-instruct") {
    $src = Join-Path $root "models\$m"
    $dst = Join-Path $app "models\$m"
    New-Item -ItemType Directory -Force $dst | Out-Null
    if (-not (Test-Path $src)) { continue }
    Get-ChildItem $src -File -Recurse | Where-Object { $_.Name -notlike "*.part" -and $_.FullName -notmatch "\.cache\\" } | ForEach-Object {
        $target = Join-Path $dst $_.FullName.Substring($src.Length + 1)
        New-Item -ItemType Directory -Force (Split-Path $target) | Out-Null
        if (-not (Test-Path $target)) { New-Item -ItemType HardLink -Path $target -Target $_.FullName | Out-Null }
    }
}

if (-not $SkipPackage) {
    & $py (Join-Path $root "tools\package_release.py")
    if ($LASTEXITCODE -ne 0) { throw "packaging failed" }
}

if (-not $SkipInstaller) {
    & powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root "installer\build.ps1")
    if ($LASTEXITCODE -ne 0) { throw "installer build failed" }
}
Write-Host "Done: $app\Tiro.exe and release\"
